### ISSUE TITLE
Debug and Refactoring about the record number handling

### ISSUE THREAD

**Issue by msyk** [INTER-Mediator/INTER-Mediator#1079]
See https://blog.msyk.net/?p=874

**Comment by matsuo** [comment]
Related Issue: #1214

**Comment by matsuo** [comment]
The order of priority in Ver. 5.8:
- 1. the value of maxrecords key
- 2. navi-control=detail
- 3. local context (pop up menu)
- 4. INTERMediator.pagedSize
- 5. the value of records key
