### ISSUE TITLE
IDE is marking an error in FMDataAPI assorted class.

### ISSUE THREAD

**Issue by msyk** [INTER-Mediator/INTER-Mediator#1244]
https://github.com/INTER-Mediator/INTER-Mediator/blob/1e58183445634115c8ba911f865373b2cef3c5e3/DB_Support/DB_Auth_Handler_FileMaker_DataAPI.php#L47

This line is as below:
$this->dbClass->$forAuth($hashTable, 1);

The "$forAuth" can't be evaluate any valid string, because "forAuth" variable is not defined. Is that "setupFMDataAPIforAuth" ?

**Comment by matsuo** [comment]
> The "$forAuth" can't be evaluate any valid string, because "forAuth" variable is not defined. Is that "setupFMDataAPIforAuth" ?

Yes. But, I think that this is not a critical bug. I will fix in Ver. 5.9.
