### ISSUE TITLE
In case of exceeding the upload file limit, IM goes into confusion? It should show appropriate message.

### ISSUE THREAD

**Issue by msyk** [INTER-Mediator/INTER-Mediator#565]
The file upload components's error handling is not appropriate. It happens on 5.3 RC1.

When the PHP reports the following message on the web logs, JS error happens and repeating task didn't finish.

PHP Warning:  POST Content-Length of 44615498 bytes exceeds the limit of 8388608 bytes in Unknown on line 0

**Comment by msyk** [comment]
This is informative. http://q.hatena.ne.jp/1193396523

**Comment by matsuo** [comment]
I have confirmed with INTER-Mediator 5.2, too.

**Comment by msyk** [comment]
Handled on 46e016f628f7c24e623d4edff3e90e922a37d635.
