### ISSUE TITLE
File uploading and FileMaker

### ISSUE THREAD

**Issue by msyk** [INTER-Mediator/INTER-Mediator#88]
Support uploading a file to FileMaker's container field when using FileMaker Server 13.

**Comment by matsuo** [comment]
INTER-Mediator 5.1 will support uploading a file to FileMaker's container field when using FileMaker Server 13.

Related commits:
61e0f09cd24dc109a85f8702b7e94c165d42cd3a
976f12bf30e79b97171bf1c1e879cd59e79e0912
5549f76a53c19cd05bb7bd2d85a79d33d5c41534

Related pages:
http://inter-mediator.info/ja/for-programmers/jscomponent.html
http://inter-mediator.info/ja/for-developers/reference.html#section001

**Comment by matsuo** [comment]
Currently Mobile Safari is not supported. I reopened this issue.

**Comment by matsuo** [comment]
Improved the compatibility with file upload component and Mobile Safari.
1f40edbf09d6dae545b2d87a1573cfe48a705129

**Comment by matsuo** [comment]
Considered upload_tmp_dir directive in php.ini. (#322)
